name: Sync Version Branches

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        # Sync main to version-specific branches
        version-branch: [main_version2]
        
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
    - name: Sync with version branch
      run: |
        # Fetch all branches
        git fetch origin
        
        # Checkout the version branch (create if doesn't exist)
        git checkout -B ${{ matrix.version-branch }} origin/${{ matrix.version-branch }} || git checkout -b ${{ matrix.version-branch }}
        
        # Merge main into version branch, preserving version-specific files
        git merge origin/main --no-edit || {
          echo "Merge conflict detected, resolving..."
          
          # Update site-version.js for version_2 branch
          if [[ "${{ matrix.version-branch }}" == "main_version2" ]]; then
            # Update the default version to version_2
            sed -i 's/VERSION_1: '\''version_1'\''/VERSION_2: '\''version_2'\''/g' src/scripts/site-version.js
            sed -i 's/DEFAULT_VERSION = SITE_VERSIONS.VERSION_1/DEFAULT_VERSION = SITE_VERSIONS.VERSION_2/g' src/scripts/site-version.js
            sed -i 's/Primary deployment is version_1/Primary deployment is version_2/g' src/scripts/site-version.js
          fi
          
          # Add the resolved files
          git add src/scripts/site-version.js
          
          # Complete the merge
          git commit -m "Auto-sync from main: configure for ${{ matrix.version-branch }}"
        }
        
        # Push the updated branch
        git push origin ${{ matrix.version-branch }}
        
    - name: Create PR for manual review (if conflicts)
      if: failure()
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: auto-sync-${{ matrix.version-branch }}-${{ github.sha }}
        title: "Auto-sync main to ${{ matrix.version-branch }} (manual review needed)"
        body: |
          Automated sync from main branch to ${{ matrix.version-branch }} encountered conflicts.
          Please review and merge manually.
          
          Source commit: ${{ github.sha }}
